### PR TITLE
Add get_user_classes convenience method

### PR DESCRIPTION
**Pull request by blx**
`get_user_profile` returns a huge chunk of JSON; here's a method to just get a list of the user's classes.

I got rid of the `get_instructor_stats` method I had previously after realizing the only new information it provides over `get_stats` is the number of unanswered followups and unanswered questions.

### CODE REVIEW

**Comment by GitCop** [comment]
There were the following issues with your Pull Request

 * Commit: 423bdea57c335e044555d4dab44e7fa435473e32
  * Commits must be in the following format: **%{type}(%{scope}): %{description}**

 * Commit: 7e135457fa4d2f3a41b742f8b391485dea7358ae
  * Commits must be in the following format: **%{type}(%{scope}): %{description}**

 * Commit: b25357b28582210b3516663c8ea245604d3cc83b
  * Commits must be in the following format: **%{type}(%{scope}): %{description}**

 * Commit: a62d3da25909b7d92a8592f23a626a26af7742b5
  * Commits must be in the following format: **%{type}(%{scope}): %{description}**

 * Commit: a6ca7f1772f80bc9349e795cde367ca013cfb3ca
  * Commits must be in the following format: **%{type}(%{scope}): %{description}**

 * Commit: 830d9258c04eef4d1b3574f653ca0781d747e819
  * Commits must be in the following format: **%{type}(%{scope}): %{description}**

 * Commit: 1fe5c2d6e652a57a18183f11b538b4a1e0a71a98
  * Commits must be in the following format: **%{type}(%{scope}): %{description}**

 * Commit: 63f1520601f4042fda2aa5074ed5771ad4b1824e
  * Commits must be in the following format: **%{type}(%{scope}): %{description}**

 * Commit: 6d0ffe7e0116c93fb73865aa425c99c31fb07a19
  * Commits must be in the following format: **%{type}(%{scope}): %{description}**

 * Commit: ccbfa15062db446b06540b984202673223c87923
  * Commits must be in the following format: **%{type}(%{scope}): %{description}**

 * Commit: 784a9b630f9ef789a382bdc6d46f34fbcd70cb0b
  * Commits must be in the following format: **%{type}(%{scope}): %{description}**

 * Commit: d84bcda925110f6daad0855d7c489b6635fa3e58
  * Commits must be in the following format: **%{type}(%{scope}): %{description}**

 * Commit: 6dcaafb3f991a073321c647b0f15e17763980e57
  * Commits must be in the following format: **%{type}(%{scope}): %{description}**

Guidelines are available at https://github.com/hfaran/piazza-api

---
This message was auto-generated by https://gitcop.com

**Comment by blx** [comment]
Going to flatten these commits and provide a message to make GitCop happy.

**Comment by hfaran** [comment]
Was going to suggest that flattening might be useful here :P

And I should put commit message guidelines in the README; I will do that now.

**Comment by hfaran** [comment]
[Guidelines added](https://github.com/hfaran/piazza-api/commit/742fdd1c4fa2a2db427860994cdafcccd1e518d8).

**Pull request closed without merging**
