### PR TITLE
feat(user): Add answer-creating functionality

### PR DESCRIPTION
**Pull request by DavidSnider**
I added the ability to create an answer to a post. It's based on work done by @arxanas on [followup creation](https://github.com/hfaran/piazza-api/pull/25), and the results are fairly similar, except for answers rather than followups.

### CODE REVIEW

**Comment by arxanas** [comment]
Can this toggle between student and instructor answers? What is the behavior about that right now? (I'm guessing `i_answer` means instructor answer?)

**Comment by DavidSnider** [comment]
You make a good point, I'm going to change this to clarify instructor answer, which is what this deals with.

**Comment by GitCop** [comment]
There were the following issues with your Pull Request

 * Commit: 04aa9e8926f41ae4915280134a4c53963f5e6424
  * Commits must be in the following format: **%{type}(%{scope}): %{description}**

Guidelines are available at https://github.com/hfaran/piazza-api

---
This message was auto-generated by https://gitcop.com

**Comment by hfaran** [comment]
Looks good to me! Has the point @arxanas brought up been resolved or are you still addressing that?

**Comment by DavidSnider** [comment]
I changed the code so it's clear that this is for instructor's responses. I didn't do student responses as I didn't have any easy way to test and I couldn't think of a good reason I'd want to be automating student responses.

**Comment by hfaran** [comment]
Yeah, that makes sense. I will go ahead and merge this then.

**Comment by arxanas** [comment]
Can we get this on PyPI?

**Comment by hfaran** [comment]
@arxanas Sure thing. I'll make a new release.

**Comment by hfaran** [comment]
0.5.2 has been released and pushed to PyPI. @DavidSnider I've added you to the contributors list. :)

**Pull request merged**
