### PR TITLE
fix(dev): Added support for the Piazza API nonce "aid" introduced recently.

### PR DESCRIPTION
**Pull request by jlumbroso**
Added support for the nonces that the Piazza API uses, see for instance [line 14-15 of this script](https://piazza.com/modules/ajax.js?v=2274):
>  var API_URL = '/logic/api?method=generic.report_js_error&aid=' +
>    (new Date()).getTime().toString(36) + Math.round(Math.random() * 1679616).toString(36);

I abstracted this functionality in a separate `nonce.py` submodule and integrated in the `rpc.py` ``request`` function which actually places the API requests, so that all methods are "signed" in this way.

(PS: Many thanks for the open source implementation of this API wrapper!)

### CODE REVIEW

**Comment by GitCop** [comment]
There were the following issues with your Pull Request

 * Commit: 170005764c72e26ab2825e8473285c11efde8e0d
  * Commits must be in the following format: **%{type}(%{scope}): %{description}**

Guidelines are available at https://github.com/hfaran/piazza-api

---
This message was auto-generated by https://gitcop.com

**Comment by GitCop** [comment]
There were the following issues with your Pull Request

 * Commit: 170005764c72e26ab2825e8473285c11efde8e0d
  * Commits must be in the following format: **%{type}(%{scope}): %{description}**

 * Commit: 1e7a5bbb3b25c23ed5ed7ef663eb2d49af98906f
  * Invalid type. Valid types are **feat, fix, docs, style, refactor, perf, test, chore, revert**

Guidelines are available at https://github.com/hfaran/piazza-api

---
This message was auto-generated by https://gitcop.com

**Comment by GitCop** [comment]
There were the following issues with your Pull Request

 * Commit: 170005764c72e26ab2825e8473285c11efde8e0d
  * Commits must be in the following format: **%{type}(%{scope}): %{description}**

 * Commit: 1e7a5bbb3b25c23ed5ed7ef663eb2d49af98906f
  * Invalid type. Valid types are **feat, fix, docs, style, refactor, perf, test, chore, revert**

 * Commit: 8442d41ab4d68b424f3f10dd24ebd0bd8b9cce0e
  * Invalid type. Valid types are **feat, fix, docs, style, refactor, perf, test, chore, revert**

Guidelines are available at https://github.com/hfaran/piazza-api

---
This message was auto-generated by https://gitcop.com

**Comment by GitCop** [comment]
There were the following issues with your Pull Request

 * Commit: 170005764c72e26ab2825e8473285c11efde8e0d
  * Commits must be in the following format: **%{type}(%{scope}): %{description}**

 * Commit: 1e7a5bbb3b25c23ed5ed7ef663eb2d49af98906f
  * Invalid type. Valid types are **feat, fix, docs, style, refactor, perf, test, chore, revert**

 * Commit: 8442d41ab4d68b424f3f10dd24ebd0bd8b9cce0e
  * Invalid type. Valid types are **feat, fix, docs, style, refactor, perf, test, chore, revert**

 * Commit: dead8c3d26ec08974dfa17e498f82079d53f8276
  * Invalid type. Valid types are **feat, fix, docs, style, refactor, perf, test, chore, revert**

Guidelines are available at https://github.com/hfaran/piazza-api

---
This message was auto-generated by https://gitcop.com

**Comment by hfaran** [comment]
Thanks! Merged.

**Pull request merged**
